production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      max_retries_on_connection_failure: 20
      persist_in_safe_mode: true
      skip_version_check: true

development:
  sessions:
    default:
      hosts:
        - localhost
      database: totally_development

test:
  sessions:
    default:
      hosts:
        - localhost
      database: totally_test